server:
  port: 8081

spring:
  application:
    name: argus-java-analyzer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
