/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 返回服务存活状态。
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description 就绪探针：依次检查 DB、事件总线、Worker。
         */
        get: operations["readiness_check_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description 返回运行指标（EventBus、队列、Worker）。
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description 列出项目。
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description 创建项目。
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description 查询项目详情。
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        /**
         * Update Project
         * @description 更新项目。
         */
        put: operations["update_project_api_v1_projects__project_id__put"];
        post?: never;
        /**
         * Delete Project
         * @description 删除项目。
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description 列出任务（轻量，不含日志和发现项），支持过滤和分页。
         */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description 创建任务快照，不立即启动执行。
         */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description 查询任务详情。
         */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        /**
         * Update Task
         * @description 更新待执行任务的基础信息。
         */
        put: operations["update_task_api_v1_tasks__task_id__put"];
        post?: never;
        /**
         * Delete Task
         * @description 删除未启动的 pending 任务。
         */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/infer-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Infer Limits
         * @description 根据任务目标和起始 URL 推断推荐的最大步数和超时时间。
         */
        get: operations["infer_limits_api_v1_tasks_infer_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description 返回仪表盘聚合统计。
         *
         *     与分页列表解耦：COUNT 走 SQLite 索引，避免 dashboard 把"当前页"误当全量。
         */
        get: operations["get_dashboard_stats_api_v1_tasks_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Task
         * @description 将 pending 任务加入后台执行队列。
         */
        post: operations["start_task_api_v1_tasks__task_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Task
         * @description 重试失败/超时/取消的任务，创建新任务并立即入队。
         */
        post: operations["restart_task_api_v1_tasks__task_id__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Task
         * @description 取消任务。支持 pending、queued 和 running 状态。
         */
        post: operations["cancel_task_api_v1_tasks__task_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Task
         * @description 暂停运行中的任务。
         */
        post: operations["pause_task_api_v1_tasks__task_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Task
         * @description 恢复暂停的任务。
         */
        post: operations["resume_task_api_v1_tasks__task_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Report
         * @description 返回任务报告文件，默认 HTML，可通过 format=json 获取结构化报告。
         */
        get: operations["get_task_report_api_v1_tasks__task_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/report.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Report Json
         * @description 返回任务 JSON 报告文件。
         */
        get: operations["get_task_report_json_api_v1_tasks__task_id__report_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/screenshots/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Screenshot
         * @description 返回任务截图文件。
         */
        get: operations["get_task_screenshot_api_v1_tasks__task_id__screenshots__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Summary
         * @description 返回非敏感配置摘要。
         */
        get: operations["get_config_summary_api_v1_config_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Model Configs
         * @description 列出模型配置。
         */
        get: operations["list_model_configs_api_v1_config_models_get"];
        put?: never;
        /**
         * Create Model Config
         * @description 创建模型配置。
         */
        post: operations["create_model_config_api_v1_config_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/models/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Model Config
         * @description 测试已保存或临时模型配置。
         */
        post: operations["test_model_config_api_v1_config_models_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/models/{model_config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Config
         * @description 查询模型配置详情。
         */
        get: operations["get_model_config_api_v1_config_models__model_config_id__get"];
        /**
         * Update Model Config
         * @description 更新模型配置。
         */
        put: operations["update_model_config_api_v1_config_models__model_config_id__put"];
        post?: never;
        /**
         * Delete Model Config
         * @description 删除模型配置。
         */
        delete: operations["delete_model_config_api_v1_config_models__model_config_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Task Events
         * @description 返回任务的执行时间线事件。
         */
        get: operations["list_task_events_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/llm-traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Llm Traces
         * @description 返回任务的 LLM 调用追踪记录。
         */
        get: operations["list_llm_traces_api_v1_tasks__task_id__llm_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/llm-traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace Detail
         * @description 返回单条 LLM 调用的完整追踪记录。
         */
        get: operations["get_trace_detail_api_v1_tasks__task_id__llm_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/debug-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Debug Bundle
         * @description 下载任务调试包（task.json + traces + 事件 + 截图）。
         */
        get: operations["download_debug_bundle_api_v1_tasks__task_id__debug_bundle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Prompt
         * @description 按角色返回拼接后的完整 system_prompt，用于编辑器预览。
         */
        post: operations["preview_prompt_api_v1_prompts_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConfigSummaryResponse
         * @description 配置摘要响应，不包含敏感值。
         */
        ConfigSummaryResponse: {
            /** Serverhost */
            serverHost: string;
            /** Serverport */
            serverPort: number;
            /** Corsalloworigins */
            corsAllowOrigins: string[];
            /** Schedulerconcurrency */
            schedulerConcurrency: number;
            /** Schedulerqueuemaxsize */
            schedulerQueueMaxSize: number;
            /** Schedulershutdowntimeoutseconds */
            schedulerShutdownTimeoutSeconds: number;
            /** Eventshistorylimit */
            eventsHistoryLimit: number;
            /** Eventssubscriberqueuesize */
            eventsSubscriberQueueSize: number;
            /**
             * Modelconfigscount
             * @default 0
             */
            modelConfigsCount: number;
            /** Defaultmodelconfigid */
            defaultModelConfigId?: string | null;
        };
        /**
         * DashboardStatsResponse
         * @description 仪表盘聚合统计响应。
         *
         *     与 ``GET /tasks`` 的分页列表解耦：``tasks_total`` / ``running_total`` 走 COUNT，
         *     不受当前页 ``limit`` 影响；``recent_tasks`` 单独返回最近 N 条 summary。
         */
        DashboardStatsResponse: {
            /** Taskstotal */
            tasksTotal: number;
            /** Runningtotal */
            runningTotal: number;
            /** Findingstotal */
            findingsTotal: number;
            /** Recenttasks */
            recentTasks?: components["schemas"]["TaskSummaryResponse"][];
        };
        /**
         * FindingResponse
         * @description 问题记录响应。
         */
        FindingResponse: {
            /** Findingid */
            findingId: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            severity: components["schemas"]["FindingSeverity"];
            findingType: components["schemas"]["FindingType"];
            /** Url */
            url?: string | null;
            /** Location */
            location?: string | null;
            /** Screenshotpath */
            screenshotPath?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * FindingSeverity
         * @description 问题严重级别。
         * @enum {string}
         */
        FindingSeverity: "critical" | "high" | "medium" | "low" | "info";
        /**
         * FindingType
         * @description 问题分类。
         * @enum {string}
         */
        FindingType: "functional" | "visual" | "performance" | "security" | "accessibility" | "error";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 健康检查响应。
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Project */
            project: string;
        };
        /**
         * InferredLimitsResponse
         * @description 推断的任务执行限制响应。
         */
        InferredLimitsResponse: {
            /** Maxsteps */
            maxSteps: number;
            /** Timeoutseconds */
            timeoutSeconds: number;
        };
        /**
         * MetricsResponse
         * @description 运行指标响应。
         */
        MetricsResponse: {
            /** Event Bus */
            event_bus: {
                [key: string]: number;
            };
            /** Total Tasks */
            total_tasks: number;
            /** Running Tasks */
            running_tasks: number;
            /** Queued Tasks */
            queued_tasks: number;
            /** Worker Alive */
            worker_alive: boolean;
            /**
             * Io Executor Queued
             * @default -1
             */
            io_executor_queued: number;
        };
        /**
         * ModelConfigCreateRequest
         * @description 创建模型配置请求。
         */
        ModelConfigCreateRequest: {
            /** Name */
            name: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /** Model */
            model: string;
            /**
             * Apikey
             * @default
             */
            apiKey: string;
            /** Baseurl */
            baseUrl?: string | null;
            /** Completionspath */
            completionsPath?: string | null;
            /** Maxretries */
            maxRetries?: number | null;
            /** Timeoutseconds */
            timeoutSeconds?: number | null;
            taskType?: components["schemas"]["TaskType"] | null;
            /**
             * Isdefault
             * @default false
             */
            isDefault: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * ModelConfigListResponse
         * @description 模型配置列表响应。
         */
        ModelConfigListResponse: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Models */
            models?: components["schemas"]["ModelConfigResponse"][];
        };
        /**
         * ModelConfigResponse
         * @description 模型配置响应，不返回 API Key 明文。
         */
        ModelConfigResponse: {
            /** Modelconfigid */
            modelConfigId: string;
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Apikeyset */
            apiKeySet: boolean;
            /** Baseurl */
            baseUrl: string;
            /** Completionspath */
            completionsPath: string;
            /** Maxretries */
            maxRetries: number;
            /** Timeoutseconds */
            timeoutSeconds: number;
            taskType?: components["schemas"]["TaskType"] | null;
            /** Isdefault */
            isDefault: boolean;
            /** Enabled */
            enabled: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ModelConfigTestRequest
         * @description 模型连接检查请求。
         */
        ModelConfigTestRequest: {
            /** Modelconfigid */
            modelConfigId?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Completionspath */
            completionsPath?: string | null;
            /** Maxretries */
            maxRetries?: number | null;
            /** Timeoutseconds */
            timeoutSeconds?: number | null;
        };
        /**
         * ModelConfigUpdateRequest
         * @description 更新模型配置请求。
         */
        ModelConfigUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Completionspath */
            completionsPath?: string | null;
            /** Maxretries */
            maxRetries?: number | null;
            /** Timeoutseconds */
            timeoutSeconds?: number | null;
            taskType?: components["schemas"]["TaskType"] | null;
            /** Isdefault */
            isDefault?: boolean | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * ModelConnectionTestResponse
         * @description 模型连接检查响应。
         */
        ModelConnectionTestResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Model */
            model?: string | null;
            /** Latencyms */
            latencyMs?: number | null;
        };
        /**
         * ProjectCreateRequest
         * @description 创建项目请求。
         */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Giturl */
            gitUrl?: string | null;
            /** Authstatename */
            authStateName?: string | null;
            /** Defaultmaxsteps */
            defaultMaxSteps?: number | null;
            /** Defaulttimeoutseconds */
            defaultTimeoutSeconds?: number | null;
            /**
             * Defaultcapturescreenshots
             * @default true
             */
            defaultCaptureScreenshots: boolean;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /**
         * ProjectListResponse
         * @description 项目列表响应。
         */
        ProjectListResponse: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Projects */
            projects?: components["schemas"]["ProjectResponse"][];
        };
        /**
         * ProjectResponse
         * @description 项目响应。
         */
        ProjectResponse: {
            /** Projectid */
            projectId: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Giturl */
            gitUrl?: string | null;
            /** Authstatename */
            authStateName?: string | null;
            /** Defaultmaxsteps */
            defaultMaxSteps?: number | null;
            /** Defaulttimeoutseconds */
            defaultTimeoutSeconds?: number | null;
            /** Defaultcapturescreenshots */
            defaultCaptureScreenshots: boolean;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ProjectUpdateRequest
         * @description 更新项目请求。
         */
        ProjectUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Giturl */
            gitUrl?: string | null;
            /** Authstatename */
            authStateName?: string | null;
            /** Defaultmaxsteps */
            defaultMaxSteps?: number | null;
            /** Defaulttimeoutseconds */
            defaultTimeoutSeconds?: number | null;
            /** Defaultcapturescreenshots */
            defaultCaptureScreenshots?: boolean | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PromptPreviewRequest
         * @description Prompt 扩展拼接预览请求。
         */
        PromptPreviewRequest: {
            /**
             * Role
             * @description 预览的 Prompt 角色：planner 或 evaluator
             * @enum {string}
             */
            role: "planner" | "evaluator";
            /**
             * Projectextension
             * @description 项目级扩展，最长 64KB
             * @default
             */
            projectExtension: string;
            /**
             * Taskextension
             * @description 任务级扩展，最长 64KB
             * @default
             */
            taskExtension: string;
        };
        /**
         * PromptPreviewResponse
         * @description Prompt 扩展拼接预览响应。
         */
        PromptPreviewResponse: {
            /** Systemprompt */
            systemPrompt: string;
            /** Builtinlength */
            builtinLength: number;
            /** Projectlength */
            projectLength: number;
            /** Tasklength */
            taskLength: number;
        };
        /**
         * ReadinessResponse
         * @description 就绪检查响应。
         */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
            /** Worker */
            worker: string;
            /** Event Bus */
            event_bus: string;
        };
        /**
         * StepResult
         * @description 步骤执行结果。
         * @enum {string}
         */
        StepResult: "success" | "failed" | "skipped";
        /**
         * TaskCreateRequest
         * @description 创建任务请求。
         */
        TaskCreateRequest: {
            /** Goal */
            goal: string;
            /** Name */
            name?: string | null;
            /** Starturl */
            startUrl?: string | null;
            /** @default blackbox */
            taskType: components["schemas"]["TaskType"];
            /** Projectid */
            projectId: string;
            /** Maxsteps */
            maxSteps?: number | null;
            /** Timeoutseconds */
            timeoutSeconds?: number | null;
            /** Capturescreenshots */
            captureScreenshots?: boolean | null;
            /** Modelconfigid */
            modelConfigId?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /**
         * TaskLogResponse
         * @description 任务步骤日志响应。
         */
        TaskLogResponse: {
            /** Stepnumber */
            stepNumber: number;
            /** Action */
            action: string;
            result: components["schemas"]["StepResult"];
            /** Tasklogid */
            taskLogId: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Urlbefore */
            urlBefore?: string | null;
            /** Urlafter */
            urlAfter?: string | null;
            /** Screenshotpath */
            screenshotPath?: string | null;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /**
         * TaskResponse
         * @description 任务详情响应（含步骤日志和发现项）。
         */
        TaskResponse: {
            /** Taskid */
            taskId: string;
            /** Projectid */
            projectId?: string | null;
            /** Goal */
            goal: string;
            /** Name */
            name?: string | null;
            /** Starturl */
            startUrl?: string | null;
            taskType: components["schemas"]["TaskType"];
            status: components["schemas"]["TaskStatus"];
            /** Schedulerstatus */
            schedulerStatus?: string | null;
            /** Maxsteps */
            maxSteps: number;
            /** Timeoutseconds */
            timeoutSeconds: number;
            /** Capturescreenshots */
            captureScreenshots: boolean;
            /** Currentstep */
            currentStep: number;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Reportpath */
            reportPath?: string | null;
            /** Resultsummary */
            resultSummary?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Logs */
            logs: components["schemas"]["TaskLogResponse"][];
            /** Findings */
            findings: components["schemas"]["FindingResponse"][];
        };
        /**
         * TaskStartResponse
         * @description 任务启动响应。
         */
        TaskStartResponse: {
            /** Schedulerstatus */
            schedulerStatus: string;
            task: components["schemas"]["TaskResponse"];
        };
        /**
         * TaskStatus
         * @description 任务生命周期状态。
         * @enum {string}
         */
        TaskStatus: "pending" | "running" | "paused" | "completed" | "failed" | "timeout" | "cancelled";
        /**
         * TaskSummaryListResponse
         * @description 轻量任务列表响应。
         */
        TaskSummaryListResponse: {
            /** Total */
            total: number;
            /** Tasks */
            tasks: components["schemas"]["TaskSummaryResponse"][];
        };
        /**
         * TaskSummaryResponse
         * @description 轻量任务响应（不含日志和发现项），供列表页使用。
         */
        TaskSummaryResponse: {
            /** Taskid */
            taskId: string;
            /** Projectid */
            projectId?: string | null;
            /** Goal */
            goal: string;
            /** Name */
            name?: string | null;
            /** Starturl */
            startUrl?: string | null;
            taskType: components["schemas"]["TaskType"];
            status: components["schemas"]["TaskStatus"];
            /** Schedulerstatus */
            schedulerStatus?: string | null;
            /** Maxsteps */
            maxSteps: number;
            /** Timeoutseconds */
            timeoutSeconds: number;
            /** Capturescreenshots */
            captureScreenshots: boolean;
            /** Currentstep */
            currentStep: number;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Reportpath */
            reportPath?: string | null;
            /** Resultsummary */
            resultSummary?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /** Findingcount */
            findingCount: number;
        };
        /**
         * TaskType
         * @description 任务类型。
         * @enum {string}
         */
        TaskType: "blackbox" | "whitebox";
        /**
         * TaskUpdateRequest
         * @description 更新任务基础信息请求。
         */
        TaskUpdateRequest: {
            /** Goal */
            goal: string;
            /** Name */
            name?: string | null;
            /** Starturl */
            startUrl?: string | null;
            /** @default blackbox */
            taskType: components["schemas"]["TaskType"];
            /** Projectid */
            projectId: string;
            /** Maxsteps */
            maxSteps?: number | null;
            /** Timeoutseconds */
            timeoutSeconds?: number | null;
            /** Capturescreenshots */
            captureScreenshots?: boolean | null;
            /** Modelconfigid */
            modelConfigId?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                projectId?: string | null;
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummaryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    infer_limits_api_v1_tasks_infer_limits_get: {
        parameters: {
            query: {
                goal: string;
                start_url?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferredLimitsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_v1_tasks_stats_get: {
        parameters: {
            query?: {
                recentLimit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_task_api_v1_tasks__task_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_task_api_v1_tasks__task_id__restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_task_api_v1_tasks__task_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_task_api_v1_tasks__task_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_report_api_v1_tasks__task_id__report_get: {
        parameters: {
            query?: {
                format?: string;
                download?: boolean;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_report_json_api_v1_tasks__task_id__report_json_get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_screenshot_api_v1_tasks__task_id__screenshots__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_summary_api_v1_config_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSummaryResponse"];
                };
            };
        };
    };
    list_model_configs_api_v1_config_models_get: {
        parameters: {
            query?: {
                includeDisabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_config_api_v1_config_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_config_api_v1_config_models_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConnectionTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_config_api_v1_config_models__model_config_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_config_api_v1_config_models__model_config_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model_config_api_v1_config_models__model_config_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_events_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_llm_traces_api_v1_tasks__task_id__llm_traces_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                trace_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_detail_api_v1_tasks__task_id__llm_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_debug_bundle_api_v1_tasks__task_id__debug_bundle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_prompt_api_v1_prompts_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
