"""阶段三：黑白盒关联 — 包初始化。"""

from argus_py.correlation.enums import (
    AttemptDiagnosticCode,
    AttemptStatus,
    BlackboxRunStatus,
    CorrelationEligibility,
    CorrelationRunStatus,
    EvidenceCompleteness,
    FindingRelationType,
    MatchConfidence,
    MatchStrategy,
    PartialReasonCode,
    RequestOutcome,
    RequestOwner,
    ResolutionStatus,
    SourceAlignmentStatus,
)
from argus_py.correlation.models import (
    BlackboxRun,
    CaptureQuality,
    CorrelationAttempt,
    CorrelationAttemptDiagnostic,
    CorrelationAttemptReason,
    CorrelationRun,
    CorrelationSummary,
    EndpointEvidence,
    EndpointEvidenceCandidate,
    EndpointEvidenceFlow,
    FindingEvidence,
    FindingEvidenceLink,
    HttpRequestEvidence,
    PathMapping,
    _CapturedRequest,
)
from argus_py.correlation.path_utils import (
    MATCHER_VERSION,
    MAX_PATH_LENGTH,
    NORMALIZATION_VERSION,
    compute_config_digest,
    compute_path_segments,
    extract_origin,
    is_path_too_long,
    normalize_for_matching,
    sanitize_for_display,
    strip_longest_segment_prefix,
)
from argus_py.correlation.validator import (
    validate_correlation_run_consistency,
    validate_endpoint_evidence,
)

__all__ = [
    # enums
    "AttemptDiagnosticCode",
    "AttemptStatus",
    "BlackboxRunStatus",
    "CorrelationEligibility",
    "CorrelationRunStatus",
    "EvidenceCompleteness",
    "FindingRelationType",
    "MatchConfidence",
    "MatchStrategy",
    "PartialReasonCode",
    "RequestOutcome",
    "RequestOwner",
    "ResolutionStatus",
    "SourceAlignmentStatus",
    # models
    "BlackboxRun",
    "CaptureQuality",
    "CorrelationAttempt",
    "CorrelationAttemptDiagnostic",
    "CorrelationAttemptReason",
    "CorrelationRun",
    "CorrelationSummary",
    "EndpointEvidence",
    "EndpointEvidenceCandidate",
    "EndpointEvidenceFlow",
    "FindingEvidence",
    "FindingEvidenceLink",
    "HttpRequestEvidence",
    "PathMapping",
    "_CapturedRequest",
    # path_utils
    "MATCHER_VERSION",
    "MAX_PATH_LENGTH",
    "NORMALIZATION_VERSION",
    "compute_config_digest",
    "compute_path_segments",
    "extract_origin",
    "is_path_too_long",
    "normalize_for_matching",
    "sanitize_for_display",
    "strip_longest_segment_prefix",
    # validator
    "validate_endpoint_evidence",
    "validate_correlation_run_consistency",
]
