"""应用级常量。"""

from argus_py.core.paths import LOGS_DIR, OUTPUT_DIR, PROMPTS_DIR, REPORTS_DIR, SCREENSHOTS_DIR, TEMP_DIR

PROJECT_NAME = "Argus"
PROJECT_VERSION = "0.1.0"
PROJECT_TAGLINE = "Every bug has nowhere to hide."

DEFAULT_OUTPUT_DIR = str(OUTPUT_DIR)
DEFAULT_LOGS_DIR = str(LOGS_DIR)
DEFAULT_SCREENSHOTS_DIR = str(SCREENSHOTS_DIR)
DEFAULT_REPORTS_DIR = str(REPORTS_DIR)
DEFAULT_TEMP_DIR = str(TEMP_DIR)
DEFAULT_PROMPTS_DIR = str(PROMPTS_DIR)

DEFAULT_BROWSER = "chromium"
DEFAULT_HEADLESS = False
DEFAULT_ACTION_TIMEOUT_MS = 10000
DEFAULT_NAVIGATION_TIMEOUT_MS = 30000
DEFAULT_PAGE_READY_TIMEOUT_MS = 8000
DEFAULT_PAGE_SETTLE_MS = 500

DEFAULT_LLM_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_LLM_MODEL = "qwen3.5-plus"
DEFAULT_LLM_MAX_TOKENS = 4096
DEFAULT_LLM_TEMPERATURE = 0.1
DEFAULT_LLM_MAX_RETRIES = 3

DEFAULT_MAX_STEPS = 20
DEFAULT_TASK_TIMEOUT_S = 300
